name: GitHub Pages Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build-dev --if-present

      - name: SSH-agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.GITPAGES_DEPLOY_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          repository-name: logger/xilerth.github.io
          ssh-key: true
          branch: main
          folder: dist/demo/browser
          clean: true
